const test = require('ava')
const sleepfor = require('sleepfor')
const {fosho} = require('fosho')
const flipcache = require('../src')

test('should be able to autoRemove', async t => {
  const config = flipcache.reinit()
    .to('./fixtures/.config.json')
    .dir(__dirname)
    .json()
    .load()
    .update('eh', ['some values'])
    .write()
    .autoRemove(10)

  fosho(config.absPath).exists()
  await new Promise(resolve => setTimeout(resolve, 2000))
  fosho(config.absPath).aintExists()
  t.pass()
})
