// const resolver1 = require('fliphub-helpers/src/resolve').setRoot('YOOOO')
// const resolver = require('fliphub-helpers/src/resolve').resolve('./')
// const resolver2 = require('fliphub-helpers/src/resolve').debug()
// const rooter = require('fliphub-helpers/rooter/index.js')
// const timer = require('fliphub-helpers/src/timer')
// const flags = require('fliphub-helpers/src/flags')
// timer.start('calling flags')
// const envs = flags('--env')
// const found = flags('nonExistantForAllCases')
// console.log(envs, found)
// timer.stop('calling flags').log('calling flags')
// timer.logLaps('flagger')
// require('babel-register')
